#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

//defined('YII_DEBUG') or define('YII_DEBUG', true);

ini_set('display_errors', 1);
error_reporting(E_ALL);

require(__DIR__ . '/../protected/config/mode.php');
require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/../protected/config/' . strtolower(APPLICATION_ENV) . '/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
